language: csharp
sudo: false
install: curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh
  | sh && source ~/.dnx/dnvm/dnvm.sh && dnvm upgrade
script:
- ". ./build.sh"
deploy:
  provider: releases
  api_key:
    secure: XpiQ/auMJrjwgd7uP/I6HFK7F4Yd0AUkpdud8JUoRt8ZSYKfAW31bevE0CQF7K+SKLy/OeP5Ftut4BnRDpoU0EpRZWhVn85VEOAooEF1l7iQPCS3qScx02jr8pBhRoHr3o73JS+S8GYDxf8ElJf31QilNadFxyK6EDsgabqEAAE=
  file: omnisharp.tar.gz
  skip_cleanup: true
  on:
    repo: OmniSharp/omnisharp-roslyn
    tags: true
    all_branches: true
