# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true
image: Visual Studio 2017
test: off # this turns of AppVeyor automatic searching for test-assemblies, not the actual testing
environment:
  BLOB_KEY:
    secure: Je3/ykZyjxIqPv9GEVCYlgG9u5cJE6pmmoHWpy7I7XcQr2Qh+oaGYc9GKb0uGmyX2tA/NOm/wWZI9TWZFQST+mAscxyYdP9PrD9OADP3UZckW3hAf8OHvK9gZVMFO+bK
install:
  - choco install azcopy
build_script:
  - ps: .\build.ps1 All -publish-all -archive
artifacts:
  - path: artifacts/package/*.zip
  - path: artifacts/deployment/*.zip
cache:
  - tools -> tools/packages.config
on_success:
  - ps: >-
      if ($ENV:APPVEYOR_REPO_TAG -eq 'true' -or $ENV:APPVEYOR_REPO_BRANCH -eq 'ci-push') {
        choco install azcopy }

  - ps: >-
      if ($ENV:APPVEYOR_REPO_TAG -eq 'true' -or $ENV:APPVEYOR_REPO_BRANCH -eq 'ci-push') {
        AzCopy /Source:".\artifacts\deployment" /Dest:https://roslynomnisharp.blob.core.windows.net/releases /DestKey:"$ENV:BLOB_KEY"
        AzCopy /Source:".\artifacts\package" /Dest:https://roslynomnisharp.blob.core.windows.net/releases/latest /DestKey:"$ENV:BLOB_KEY" }

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: YW4vAIFrVIdyKBNxyVGWGKHP2UejoZcTcD0cf7KYEgZefUWY2XFHjetDW4Q0cICx
    artifact: /.*\.zip/
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Slack
    auth_token:
      secure: OU7mWtP+JWLRV2Ofq3/QMQbudeN632xLgWb4zMJtOssi2v5HER4qe0GFoj/rnIYOBXd3d/5+glfKG3ijvCU3bA==
    channel: '#integrations'
