
name: 'Tests'
env:
  DotNetVersion: "3.1.402"
  NuGetVersion: "5.7.0"
  MonoVersion: "6.12.0"
  Artifacts: ${{ github.workspace }}/artifacts/
  Coverage: ${{ github.workspace }}/coverage/
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
defaults:
  run:
    shell: pwsh
on:
  pull_request:
    branches:
      - master
    tags:
      - '*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
        testProjects:
          - OmniSharp.DotNetTest.Tests
          - OmniSharp.MSBuild.Tests,OmniSharp.Roslyn.CSharp.Tests,OmniSharp.Cake.Tests,OmniSharp.Script.Tests,OmniSharp.Stdio.Tests,OmniSharp.Http.Tests,OmniSharp.Tests,OmniSharp.Lsp.Tests
    name: 'Test'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: 'false'
          fetch-depth: '0'

      - name: 🔨 Use Mono ${{ env.MonoVersion }} SDK
        uses: maxim-lobanov/setup-xamarin@v1
        with:
          mono-version: ${{ env.MonoVersion }}

      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ env.NuGetVersion }}

      - name: 🔨 Use .NET Core ${{ env.DotNetVersion }} SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ env.DotNetVersion }}

      - name: 🎁 dotnet tool restore
        run: |
          dotnet tool restore

      - name: 🎁 nuget install
        run: |
          nuget install tools/packages.config -ExcludeVersion -OutputDirectory tools

      - name: 🍰 Run Cake
        run: |
          dotnet cake --configuration Debug --verbosity Verbose --target Test --test-project="${{ matrix.testProjects }}"

      - name: ⬆ Publish Logs
        uses: actions/upload-artifact@v2
        continue-on-error: true
        if: ${{ always() }}
        with:
          name: 'logs - ${{ github.workflow }} ${{ matrix.os }}'
          path: '${{ env.Artifacts }}/logs/'
